# Generated by Django 2.1.2 on 2018-10-22 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181022_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Comuna'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Genero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_tip_vivienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tipo_Vivienda'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tipo_usuario'),
        ),
    ]
