# Generated by Django 2.1.2 on 2018-10-23 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181022_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campania',
            name='id_tip_campania',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tipo_campania'),
        ),
        migrations.AlterField(
            model_name='campania_insumo',
            name='cod_campania',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Campania'),
        ),
        migrations.AlterField(
            model_name='campania_insumo',
            name='id_insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Insumo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='id_tip_insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tipo_insumo'),
        ),
        migrations.AlterField(
            model_name='login',
            name='rut_trabajador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Trabajador'),
        ),
        migrations.AlterField(
            model_name='login',
            name='rut_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='cod_refugio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Refugio'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='id_orig_masc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Origen_mascota'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='id_raza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Raza'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='rut_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='id_comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Comuna'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='id_genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Genero'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='id_fondo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Fondo_Economico'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='rut_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AlterField(
            model_name='visita_adopcion',
            name='cod_compania',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Campania'),
        ),
        migrations.AlterField(
            model_name='visita_adopcion',
            name='cod_mascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Mascota'),
        ),
        migrations.AlterField(
            model_name='visita_adopcion',
            name='rut_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AlterField(
            model_name='visita_medica',
            name='cod_mascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Mascota'),
        ),
        migrations.AlterField(
            model_name='visita_medica',
            name='rut_trabajador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Trabajador'),
        ),
    ]
