# Generated by Django 2.0.7 on 2018-10-24 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181023_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='id_genero',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comuna'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_genero',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_tip_vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tipo_Vivienda'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tipo_usuario'),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
