# Generated by Django 2.1.2 on 2018-10-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181023_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='rut_usuario',
            field=models.CharField(max_length=20),
        ),
    ]
